import 'package:flutter/material.dart';

class CustomColorsUtils {

  Map<String, Color> colorMap = {
    'Transparent' : Colors.transparent,
    "Black": Colors.black,
    "White": Colors.white,
    "Blue": Colors.blue,
    "Pink": Colors.pink,
    "Clear": Colors.transparent,
    "Silver": Colors.grey,
    "Violet": Colors.purple,
    "Gold": Colors.amber,
    "Red": Colors.red,
    "Orange": Colors.orange,
    "Yellow": Colors.yellow,
    "Olive": Colors.green.shade800,
    "Ivory": Colors.grey.shade100,
    "Green": Colors.green,
    "Saddle Brown": const Color(0xFF8B4513),
    "Baltic Blue": const Color(0xFF1C2331),
    "California Poppy": const Color(0xFFFFA500),
    "Charcoal": const Color(0xFF36454F),
    "Fjord": const Color(0xFF0077BE),
    "Snow": const Color(0xFFFFFAFA),
    "Graphite": const Color(0xFF383838),
    "Turquoise": const Color.fromRGBO(64, 224, 208, 1.0),
    "Crimson": const Color(0xFFDC143C),
    "Azure": const Color(0xFFF0FFFF),
    "Beige": const Color(0xFFF5F5DC),
    "Bisque": const Color(0xFFFFE4C4),
    "BlanchedAlmond": const Color(0xFFFFEBCD),
    "BlueViolet": const Color(0xFF8A2BE2),
    "BurlyWood": const Color(0xFFDEB887),
    "CadetBlue": const Color(0xFF5F9EA0),
    "Chartreuse": const Color(0xFF7FFF00),
    "Chocolate": const Color(0xFFD2691E),
    "Coral": const Color(0xFFFF7F50),
    "CornflowerBlue": const Color(0xFF6495ED),
    "Cornsilk": const Color(0xFFFFF8DC),

    "Cyan": const Color(0xFF00FFFF),
    "DarkBlue": const Color(0xFF00008B),
    "DarkCyan": const Color(0xFF008B8B),
    "DarkGoldenRod": const Color(0xFFB8860B),
    "DarkGray": const Color(0xFFA9A9A9),
    "DarkGrey": const Color(0xFFA9A9A9),
    "DarkGreen": const Color(0xFF006400),
    "DarkKhaki": const Color(0xFFBDB76B),
    "DarkMagenta": const Color(0xFF8B008B),
    "DarkOliveGreen": const Color(0xFF556B2F),
    "DarkOrange": const Color(0xFFFF8C00),
    "DarkOrchid": const Color(0xFF9932CC),
    "DarkRed": const Color(0xFF8B0000),
    "DarkSalmon": const Color(0xFFE9967A),
    "DarkSeaGreen": const Color(0xFF8FBC8F),
    "DarkSlateBlue": const Color(0xFF483D8B),
    "DarkSlateGray": const Color(0xFF2F4F4F),
    "DarkSlateGrey": const Color(0xFF2F4F4F),
    "DarkTurquoise": const Color(0xFF00CED1),
    "DarkViolet": const Color(0xFF9400D3),
    "DeepPink": const Color(0xFFFF1493),
    "DeepSkyBlue": const Color(0xFF00BFFF),
    "DimGray": const Color(0xFF696969),
    "DimGrey": const Color(0xFF696969),
    "DodgerBlue": const Color(0xFF1E90FF),
    "FireBrick": const Color(0xFFB22222),
    "FloralWhite": const Color(0xFFFFFAF0),
    "ForestGreen": const Color(0xFF228B22),
    "Fuchsia": const Color(0xFFFF00FF),
    "Gainsboro": const Color(0xFFDCDCDC),
    "GhostWhite": const Color(0xFFF8F8FF),

    "GoldenRod": const Color(0xFFDAA520),
    "Gray": const Color(0xFF808080),
    "Grey": const Color(0xFF808080),

    "Brown": const Color(0xFFA52A2A),
    "Purple": Colors.purple,
    "Honeydew": const Color(0xFFF0FFF0),
    "HotPink": const Color(0xFFFF69B4),
    "IndianRed": const Color(0xFFCD5C5C),
    "Indigo": const Color(0xFF4B0082),
    "Khaki": const Color(0xFFF0E68C),
    "Lavender": const Color(0xFFE6E6FA),
    "LavenderBlush": const Color(0xFFFFF0F5),
    "LawnGreen": const Color(0xFF7CFC00),
    "LemonChiffon": const Color(0xFFFFFACD),
    "LightBlue": const Color(0xFFADD8E6),
    "LightCoral": const Color(0xFFF08080),
    "LightCyan": const Color(0xFFE0FFFF),
    "LightGoldenRodYellow": const Color(0xFFFAFAD2),
    "LightGray": const Color(0xFFD3D3D3),
    "LightGrey": const Color(0xFFD3D3D3),
    "LightGreen": const Color(0xFF90EE90),
    "LightPink": const Color(0xFFFFB6C1),
    "LightSalmon": const Color(0xFFFFA07A),
    "LightSeaGreen": const Color(0xFF20B2AA),
    "LightSkyBlue": const Color(0xFF87CEFA),
    "LightSlateGray": const Color(0xFF778899),
    "LightSlateGrey": const Color(0xFF778899),
    "LightSteelBlue": const Color(0xFFB0C4DE),
    "LightYellow": const Color(0xFFFFFFE0)
  };
  List<Color> getColorsFromStrings(List<String> colorStrings) {
    List<Color> colors = [];
    for (String colorString in colorStrings) {
      String lowerCaseColorString = colorString.toLowerCase();
      String? key = colorMap.keys.firstWhere((key) => key.toLowerCase() == lowerCaseColorString, orElse: () => 'Transparent');
      colors.add(colorMap[key] ?? Colors.transparent);
    }
    return colors;
  }
}